### PR TITLE
Add Python build for Linux on ARM architecture

### PR DESCRIPTION
**Pull request by tomviner**
**Summarize your change.**

Add support for building wheels for Linux on ARM architecture.

This covers both ARM64 hardware running Linux directly, as well as Docker containers running under other operating systems, such as Docker on MacOS.

Our use case is to speed up installs of the package in Docker running on Apple M1 MacBooks.

See docs https://cibuildwheel.pypa.io/en/stable/faq/#emulation
Note there is a time penalty to building this wheel under emulation.

### CODE REVIEW

**Comment by mmcardle** [comment]
👍

**Comment by jminor** [comment]
This sounds like a good idea. @tomviner can you just double check that this PR doesn't conflict/overlap with this which just landed? https://github.com/AcademySoftwareFoundation/OpenTimelineIO/pull/1789

**Comment by tomviner** [comment]
> This sounds like a good idea. @tomviner can you just double check that this PR doesn't conflict/overlap with this which just landed? #1789

Good point. I've added some changes to take account of this.

Now we'll see just `x86_64` and `aarch64` (and not `i686`) getting built under the Ubuntu wheels.

**Review by JeanChristopheMorinPerso — APPROVED** [review]
LGTM, thanks for creating this PR!

**Pull request merged**
