### PR TITLE
Add C++17 guard to casters.h

### PR DESCRIPTION
**Pull request by ssteinbach**
When building with C++17 turned ON, our `optional` and `any` libraries, `nonstd::optional` and `nonstd::any`, are replaced with the ones present in `std` in C++17 on.  Because Pybind11 already defines casters for the `std::optional`, this causes a build error, duplicate definition, with the definition found in casters.h.  This PR guards the definition in casters.h and adds to the comment describing why its guarded and when casters.h can be removed.

### CODE REVIEW

**Review by JeanChristopheMorinPerso — APPROVED** [review]
LGTM. I'm surprised we didn't catch that before!

**Comment by ssteinbach** [comment]
I don't think we have any C++17 builds in our CI?  which we should also add... I can file an issue for that but I won't have time to do that today

**Comment by darbyjohnston** [comment]
How far off is the next release? We were hoping to merge the "c++17" branch shortly after which will enable C++17 support and removes "casters.h":
https://github.com/AcademySoftwareFoundation/OpenTimelineIO/pull/1539

**Comment by ssteinbach** [comment]
Ah yeah.  So @darbyjohnston does this still apply in that case?  Or should we skip this entirely.

**Comment by darbyjohnston** [comment]
I'm not sure, I was hoping the new release would be out by now and we could merge the "c++17" branch which would take care of "casters.h" and enable C++17 for the CI. But if you need C++17 support now then this seems like a reasonable change.

> When building with C++17 turned ON, our optional and any libraries, nonstd::optional and nonstd::any, are replaced with the ones present in std 

How does this work, don't the includes and namespaces need to be updated as well to use the std:: versions?

**Comment by ssteinbach** [comment]
I think the trick is that the any and optional libraries get swapped out.  And since internally we hide them behind otio::optional and otio::any, if you're referring those types, they'll become std too.  

IE: 
https://github.com/martinmoene/optional-lite/blob/be720ebfd7add22abe60e49602735de9231105d0/include/nonstd/optional.hpp#L201

And yeah, this enables C++17 builds with pre landing the C++17 build.

**Comment by darbyjohnston** [comment]
Ah, that's confusing since it looks like they are still being used. Hopefully at some point we can fully migrate to C++17 and remove the dependencies.

It looks like older versions of Visual Studio on Windows didn't support the `__cplusplus` macro, though the CI builds passed so it seems to be fixed in Visual Studio 2022 at least:
https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/
https://gitlab.kitware.com/cmake/cmake/-/issues/18837

**Pull request merged**
