### PR TITLE
Support for C++17

### LINKED ISSUE #1526: Support for C++17
## Support for C++ 17

VfxPlatform CY2020 specifies C++14, but CY2021 and greater specify C++17.
We currently use c++17 shim libraries to get the functionality of optional and any.
Adopting C++17 would eliminate two dependencies from our build and thus simplify our build scripts, and simplify our build configuration.

## Description

When the next OpenTimelineIO release is tagged, we will note that it is the last release supporting CY2020.
We will go ahead at that point with removing the optional and any shims.
Should bugs arise that need to be addressed in that release for the CY2020 platform, we will create a maintenance branch and perform corrections as required in that branch. Subsequent point releases in support of CY2020 will be made against that branch.
Support for CY2020 will be dropped at the end of calendar year 2023.

## Context

Participants representing studios and vendors queried in the 2023 Jan 19 TSC meeting indicate they already building with C++17.

### PR DESCRIPTION
**Pull request by darbyjohnston**
Fixes #1526

Changes:
* Set the C++ version to 17 in the top-level CMakelist.txt file
* Replaced ```any``` and ```optional``` dependencies with versions from the standard library
* Removed the ```any``` and ```optional``` dependencies

I noticed there was a comment in ```src/py-opentimelineio/bindings-common/casters.h``` about some Python binding code that could be removed with moving to C++17. Is there any additional code that can be removed?

### CODE REVIEW

**Comment by darbyjohnston** [comment]
The CI error on macOS is:
```
/Users/runner/work/OpenTimelineIO/OpenTimelineIO/src/opentimelineio/serializableObject.h:241:40: error: 'any_cast<const opentimelineio::v1_0::AnyVector &>' is unavailable: introduced in macOS 10.13
[327](https://github.com/AcademySoftwareFoundation/OpenTimelineIO/actions/runs/3964023896/jobs/6792648407#step:3:334)
                    AnyVector const& av = std::any_cast<AnyVector const&>(source);
[328](https://github.com/AcademySoftwareFoundation/OpenTimelineIO/actions/runs/3964023896/jobs/6792648407#step:3:335)
                                               ^
[329](https://github.com/AcademySoftwareFoundation/OpenTimelineIO/actions/runs/3964023896/jobs/6792648407#step:3:336)
        /Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/any:596:12: note: 'any_cast<const opentimelineio::v1_0::AnyVector &>' has been explicitly marked unavailable here
[330](https://github.com/AcademySoftwareFoundation/OpenTimelineIO/actions/runs/3964023896/jobs/6792648407#step:3:337)
        _ValueType any_cast(any const & __v)
[331](https://github.com/AcademySoftwareFoundation/OpenTimelineIO/actions/runs/3964023896/jobs/6792648407#step:3:338)
                   ^
```
It mentions macOS 10.13 which seems odd since the GitHub actions are setup to use ```macos-latest```.

**Comment by meshula** [comment]
Looking good :) As I mentioned elsewhere I think a strategy would be to land this in a feature branch so that we can play and iterate as we work towards the VFX2020 maintenance release that will allow us to cleanly break from C++14 dev.

Perhaps a peek at git logs can reveal who to summon for the note on the code to remove in the bindings (hopefully not me, as I don't recall that aspect ;) )

**Comment by JeanChristopheMorinPerso** [comment]
The note regarding pybind11 was from me. Once we use c++ 17, we can safely remove the two type casters that we had for supporting `std::optional`. Pybind11 will detect that we compile with 17 and will take care of all that magically, which means we don't need these casters anymore.

**Comment by darbyjohnston** [comment]
I fixed the macOS CI by adding a minimum version to the CMakeLists.txt:
```
set(CMAKE_OSX_DEPLOYMENT_TARGET "10.14" CACHE STRING "Minimum OS X deployment version")
```

The "docs / check-links" test is still failing, but I think that's a general issue right now?

**Comment by meshula** [comment]
@darbyjohnston by feature branch I mean _on this repo_. In other words land OpenTimelineIO:cxx17 on this repo for official support, as opposed to feature branch that exists on your repo.

**Comment by darbyjohnston** [comment]
OK, I just pushed the "cxx17" branch to the main repo.

**Comment by meshula** [comment]
@darbyjohnston Sweet :) Why don't we close this, and further iteration can be done as PRs against the branch?

**Comment by JeanChristopheMorinPerso** [comment]
If you need testers, I can probably test with my JS bindings.

**Comment by darbyjohnston** [comment]
Here is the new PR based on a branch in the main repo:
https://github.com/AcademySoftwareFoundation/OpenTimelineIO/pull/1539

@JeanChristopheMorinPerso If you have time to test with your JS bindings that would be great

**Pull request closed without merging**
