### PR TITLE
initial commit of the _core_utils tests

### PR DESCRIPTION
**Pull request by ssteinbach**
* adds unit tests for testing `_core_utils` implementation details

Co-authored by: @JeanChristopheMorinPerso

### CODE REVIEW

**Review by meshula — APPROVED** [review]
This looks fine to me, not sure if it needs to be "Draft", as some tests is better than no tests, and these all look reasonable :)

**Comment by ssteinbach** [comment]
Its draft because the tests don't all pass - I can disable the failing tests for now and we can land this though.

**Comment by JeanChristopheMorinPerso** [comment]
The missing functions can be seen at https://github.com/JeanChristopheMorinPerso/OpenTimelineIO/blob/improve_test_coverage/src/py-opentimelineio/opentimelineio-bindings/otio_tests.cpp#L160-L166

Also some tests rely on a modification to the source code if I'm not mistaken. I'll take some time tomorrow to explain what I mean and what are the modifications.

**Comment by ssteinbach** [comment]
superseded by #1436

**Pull request closed without merging**
