### PR TITLE
Added support for custom adapter hooks

### PR DESCRIPTION
**Pull request by timlehr**
**Summarize your change.**

This adds support for attributing custom hooks to adapters and executing them with `hook_function_argument_map` being passed along through the adapter IO functions.

**Describe the reason for the change.**

I added two custom hooks to the OTIO AAF adapter (https://github.com/OpenTimelineIO/otio-aaf-adapter/pull/43), allowing for embedding of media essence into the resulting AAF. This was needed to facilitate just-in-time DNXHR transcoding of the media for the AAF creation and adding a certain level of control and flexibility to the feature. 

These features to the core are required in order to properly pass the hook argument map along to potential custom hooks run by the adapter. I tried to work with `_FEATURE_MAP` instead of creating a new version of the Adapter schema in order to minimize the impact of this change, while adding the necessary changes to facilitate custom hooks for adapters.

**Reference associated tests.**

```
tests/test_adapter_plugin.py
tests/test_hooks_plugins.py
```

### CODE REVIEW

**Comment by timlehr** [comment]
@ssteinbach If you could have a look at this sometime, that'd be wonderful. See https://github.com/OpenTimelineIO/otio-aaf-adapter/pull/43 for why this is needed.

**Comment by reinecke** [comment]
@timlehr Can you [switch the base branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request) in this PR to the new `extract_adapters_post_beta_16` branch - that one was rebased on the main branch after the beta 16 release.

**Comment by timlehr** [comment]
@reinecke Just rebased the code!

**Comment by ssteinbach** [comment]
@reinecke @timlehr did the rebase capture too much stuff?  It seems like there is a lot in here -- or did the base change w/o/ rebasing?

**Comment by timlehr** [comment]
Seems like there were force-pushes to the `extract_adapters_post_beta_16` branch after I rebased, so I will have to do that again.

**Pull request closed without merging**
