### PR TITLE
Fixes and improvements for Kdenlive adapter

### PR DESCRIPTION
**Pull request by jlskuz**
**Summarize your change.**

This improves the Kdenlive adapter, most important it fixes reading of newer Kdenlive projects with same-track-tansitions ("mixes"). At the moment reading those files leads to a messed up item order in the timeline. Writing "mixes" is still a TODO, but for a different PR.

However there are more improvements:

- Add support for SMPTE bars (read and write)
- Add support for timeline markers (read and write)
- Add support for clip markers (only reading yet)
- Move some code parts to functions to improve readability, reuseasablity and testability.
- Write to Kdenlive: Add unsupported clip placeholder only if needed
- Extend tests

### CODE REVIEW

**Comment by jminor** [comment]
I'm not fluent in Kdenlive, but this change looks good from my perspective. Is there someone from the Kdenlive who would be a suitable code reviewer?

On a related note, we're working on splitting each OTIO adapter into a separate repo (see https://github.com/AcademySoftwareFoundation/OpenTimelineIO/pull/1348 for example) so that each adapter can have a separate release cycle, maintainers, etc. Do you know who would be a good person to help with that?

**Comment by jlskuz** [comment]
Thanks for the review! I am a Kdenlive developer myself. We are aware if the split of and I can help with it. If I did understand right, the Kdenlive adapter (as a contrib adapter) should not go to the OpenTimelineIO namespace, but rather to a place of the Kdenlive community? This would need some work, since Kdenlive is part of the KDE community and all source code lives in a self- hosted gitlab instance. So the CI needs to get ported to GitLab as well as the release process with pypi.org

For the review we can ask @vpinon and @j-b-m , but not sure if they are available

**Comment by vpinon** [comment]
> For the review we can ask @vpinon and @j-b-m , but not sure if they are available

Hello,

It's wonderful! Better implementation, more features and much more tests that I would have written myself :wink:
You definitely can trust @jlskuz to do great job for Kdenlive part.

I'm looking forward to the next steps (writing Kdenlive mixes, releasing the adapter autonomously).
Thanks for the hard work!

**Comment by jminor** [comment]
Glad to hear it :)
It would be fine to move the adapter into the https://github.com/OpenTimelineIO area of GitHub - you can see the [template repo for new plugins](https://github.com/OpenTimelineIO/otio-plugin-template) and the [AAF adapter move](https://github.com/AcademySoftwareFoundation/OpenTimelineIO/pull/1348) to see how that process is going.
For now though, we can go ahead and accept this PR.

**Review by jminor — APPROVED** [review]

**Comment by jlskuz** [comment]
> Glad to hear it :) It would be fine to move the adapter into the https://github.com/OpenTimelineIO area of GitHub - you can see the [template repo for new plugins](https://github.com/OpenTimelineIO/otio-plugin-template) and the [AAF adapter move](https://github.com/AcademySoftwareFoundation/OpenTimelineIO/pull/1348) to see how that process is going. For now though, we can go ahead and accept this PR.

@jminor We discussed this with the Kdenlive team and checked how difficult porting the CI is. Finally we decided that we want to move the adapter to KDE infrastructure. We are now setting everything up. I will open a pull request to remove the adapter from the core repository soon.

**Comment by ssteinbach** [comment]
Please let us know how your integration goes!

**Pull request merged**
