### PR TITLE
Fix RationalTime Representation

### LINKED ISSUE #682: RationalTime repr inexact value can be hard to debug
When the value gets large enough on a RationalTime, the repr switches to scientific notation. This can make debugging output less exact than needed in common debugging situations:

For instance, in the following example the repr appears to be three frames forward in time:
```
>>> otio.opentime.from_timecode("11:58:01:13", rate=24)
otio.opentime.RationalTime(value=1.03396e+06, rate=24)
>>> otio.opentime.from_timecode("11:58:01:13", rate=24).value
1033957.0
>>> otio.opentime.RationalTime(1033957, rate=24)
otio.opentime.RationalTime(value=1.03396e+06, rate=24)
```

### PR DESCRIPTION
**Pull request by visajshah**
Fixes #682 RationalTime Representation

### CODE REVIEW

**Comment by jminor** [comment]
Thanks for taking a look at this! Could you add some tests also to show that the intended use case (e.g. round-trip from RationalTime to string to back again) are working properly?
Also, there is some background information and suggested strategy for this here: https://stackoverflow.com/questions/16839658/printf-width-specifier-to-maintain-precision-of-floating-point-value/19897395

**Comment by visajshah** [comment]
Yeah, sure, I will look into it. I will also have to look at the build tests and clear that.

**Comment by meshula** [comment]
@visajshah Are you still interested in pursuing this one? The intention seemed worthwhile.

**Comment by meshula** [comment]
Closing due to inactivity.

**Pull request closed without merging**
