### PR TITLE
Remove Kdenlive adapter for split out

### PR DESCRIPTION
**Pull request by jlskuz**
**Summarize your change.**

As part of the ongoing outlining process of contrib adapters, this removes the Kdenlive adapter from the core repository. As discussed with the Kdenlive team (of which @vpinon, the original author, is part), the code has been moved to the KDE GitLab https://invent.kde.org/multimedia/kdenlive-opentimelineio

Related #1378

See also discussion in #1390

~_NOTE: while removing the section about AAF from docs/tutorials/otio-plugins.md is theoretically not part of this PR, it is required to make the tests pass._~

### CODE REVIEW

**Comment by meshula** [comment]
It's fantastic to see the adapter hosted at kde.org!

What's the nature of the test failure stemming from the AAF documentation block?

**Comment by jlskuz** [comment]
It is due to `docs/tutorials/otio-plugins.md` being auto-generated in sync with the code. The section about AAF was still in the doc, while the code as been (re)moved. See the first paragraph of `docs/tutorials/otio-plugins.md`:

> This document is automatically generated by running the
> `autogen_plugin_documentation` command, or by running `make plugin-model`.  It
> is part of the unit tests suite and should be updated whenever the schema
> changes.  If it needs to be updated, run: `make doc-plugins-update` and this
> file should be regenerated.

This is the (shortened) output of the test:

```
======================================================================
FAIL: test_plugin_documentation (test_serialized_schema.PluginDocumentationTester)
Verify that the plugin manifest matches what is checked into the
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/julius/Programmierung/github/OpenTimelineIO/tests/test_serialized_schema.py", line 67, in test_plugin_documentation
    self.assertMultiLineEqual(
AssertionError: '# Pl[614 chars]\n- `opentimelineio/adapters/builtin_adapters.[17532 chars]\n\n' != '# Pl[614 chars]\n- `site-packages/otio_moviemaker_adapter/plu[2903 chars]\n\n'
[...]  
 : 
 The schema has changed and the autogenerated documentation in /home/julius/Programmierung/github/OpenTimelineIO/docs/tutorials/otio-plugins.md needs to be updated.  run: `make doc-plugins-update`

----------------------------------------------------------------------
```

**Review by meshula — APPROVED** [review]

**Comment by meshula** [comment]
I'm approving, but I'd like to get a response from more of the TSC since this is a structural change to the project.

**Comment by meshula** [comment]
Assuming no one has anything to add about the AAF issue, in the spirit of "separation of concerns", would it make sense to submit the AAF documentation fix up as a PR, and rebase this one on that?

**Comment by meshula** [comment]
Note this PR which moves the AAF adapter to its own repo:

https://github.com/AcademySoftwareFoundation/OpenTimelineIO/pull/1348

**Comment by ssteinbach** [comment]
The AAF adapter is still in the repo, you shouldn't have to delete those docs.  The CI shows errors where that doc is missing:
https://github.com/AcademySoftwareFoundation/OpenTimelineIO/actions/runs/3164460045/jobs/5152761379#step:9:360

So I'm wondering if maybe some stale local state led to needing to delete it locally? They definitely should be there still.  I think everything else about this PR is good to go.

**Comment by markreidvfx** [comment]
@jlskuz  I can replicate the docs behavior if I mess up my local install of pyaaf2.  Does `python -c "import aaf2"` report error?

**Comment by jlskuz** [comment]
> @jlskuz I can replicate the docs behavior if I mess up my local install of pyaaf2. Does `python -c "import aaf2"` report a error?

That command worked just fine. It turned out that `make tests` and `make doc-plugins-update` got confused likely by the Kdenlive adapter and the AAF adapter I had installed separately from their new repos. After I uninstalled them and reset my OpenTimelineIO git clone, it worked properly.

I just force pushed the fix, it should be okay now.

**Comment by ssteinbach** [comment]
Thank you!

**Pull request merged**
