### PR TITLE
Support for C++17

### LINKED ISSUE #1526: Support for C++17
## Support for C++ 17

VfxPlatform CY2020 specifies C++14, but CY2021 and greater specify C++17.
We currently use c++17 shim libraries to get the functionality of optional and any.
Adopting C++17 would eliminate two dependencies from our build and thus simplify our build scripts, and simplify our build configuration.

## Description

When the next OpenTimelineIO release is tagged, we will note that it is the last release supporting CY2020.
We will go ahead at that point with removing the optional and any shims.
Should bugs arise that need to be addressed in that release for the CY2020 platform, we will create a maintenance branch and perform corrections as required in that branch. Subsequent point releases in support of CY2020 will be made against that branch.
Support for CY2020 will be dropped at the end of calendar year 2023.

## Context

Participants representing studios and vendors queried in the 2023 Jan 19 TSC meeting indicate they already building with C++17.

### PR DESCRIPTION
**Pull request by darbyjohnston**
Fixes #1526

Changes:

* Set the C++ version to 17 and CMAKE_OSX_DEPLOYMENT_TARGET to 10.14 in the top-level CMakelist.txt file
* Replaced any and optional dependencies with versions from the standard library
* Removed the any and optional dependencies

(This PR replaces https://github.com/AcademySoftwareFoundation/OpenTimelineIO/pull/1530)

### CODE REVIEW

**Comment by darbyjohnston** [comment]
The PR is still showing conflicts even though the latest changes from main have been merged. Maybe the DCO failing is causing the conflicts to not be updated?

**Comment by meshula** [comment]
It's possible. Are you able to rewrite the commits for these?

Commit sha: [e6a9313](https://github.com/AcademySoftwareFoundation/OpenTimelineIO/pull/1539/commits/e6a9313e9f70f1771e8299719e98208cf5db9d06), Author: Darby Johnston, Committer: GitHub; The sign-off is missing.
Commit sha: [0e10458](https://github.com/AcademySoftwareFoundation/OpenTimelineIO/pull/1539/commits/0e104580edc5f868aa2900a55954eb9ed5a40d8a), Author: Darby Johnston, Committer: GitHub; The sign-off is missing.

**Comment by peter-targett** [comment]
+1 to get this back to the main-line branch.

**Comment by jminor** [comment]
I pressed the "Set DCO to pass" button, since @darbyjohnston has clearly asserted that these commits are fine.

**Review by meshula — APPROVED** [review]

**Comment by reinecke** [comment]
Superseded by #1713

**Pull request closed without merging**
